### ISSUE TITLE
Initialization?

### ISSUE THREAD

**Issue by fractaledmind** [philgruneich/littlefoot#1]
I'm interested in trying this out (even tho I've seen that `bigfoot.js` is working on a non-jQuery version). However, I'm uncertain how to actually get it to run. If this is how you initialize `bigfoot`:

```
<script type="text/javascript">
    $.bigfoot();
</script>
```

How do you initialize `littlefoot`?

**Comment by philgruneich** [comment]
I`m so sorry @smargh, I haven't looked much to this project and I had notifications turned off. I just pushed a bunch of updates and the compiled version of the script can be initialized like this:

```
<script>
  lf = new LittleFoot();
  lf.init();
</script>
```
